SRCS=\
	CompressDialog.cpp \
	CompressDialog_rc.cpp \
	ExtractDialog.cpp \
	ExtractDialog_rc.cpp \
	BenchmarkDialog.cpp \
	BenchmarkDialog_rc.cpp \
	ExtractGUI.cpp \
	GUI.cpp \
	wxGUI.cpp \
	UpdateCallbackGUI.cpp \
	UpdateGUI.cpp \
	../Common/ArchiveCommandLine.cpp \
	../Common/ArchiveExtractCallback.cpp \
	../Common/ArchiveOpenCallback.cpp \
	../Common/DefaultName.cpp \
	../Common/EnumDirItems.cpp \
	../Common/Extract.cpp \
	../Common/ExtractingFilePath.cpp \
	../Common/LoadCodecs.cpp \
	../Common/OpenArchive.cpp \
	../Common/PropIDUtils.cpp \
	../Common/SetProperties.cpp \
	../Common/SortUtils.cpp \
	../Common/TempFiles.cpp \
	../Common/Update.cpp \
	../Common/UpdateAction.cpp \
	../Common/UpdateCallback.cpp \
	../Common/UpdatePair.cpp \
	../Common/UpdateProduce.cpp \
	../Common/WorkDir.cpp \
	../Common/ZipRegistry.cpp \
	../Explorer/MyMessages.cpp \
	../FileManager/FormatUtils.cpp \
	../FileManager/ProgramLocation.cpp \
	../FileManager/ProgressDialog2.cpp \
	../FileManager/ProgressDialog2_rc.cpp \
	../FileManager/MessagesDialog.cpp \
	../FileManager/MessagesDialog_rc.cpp \
	../FileManager/OverwriteDialog.cpp \
	../FileManager/OverwriteDialog_rc.cpp \
	../FileManager/PasswordDialog.cpp \
	../FileManager/PasswordDialog_rc.cpp \
	../FileManager/ExtractCallback.cpp \
	../FileManager/SplitUtils.cpp \
	../FileManager/StringUtils.cpp \
	../FileManager/LangUtils.cpp \
	../../Common/FilePathAutoRename.cpp \
	../../Common/FileStreams.cpp \
	../../Common/ProgressUtils.cpp \
	../../Common/StreamUtils.cpp \
	../../Compress/CopyCoder.cpp \
	../../Compress/LZMA_Alone/LzmaBench.cpp \
	../../../Common/CommandLineParser.cpp \
	../../../Common/CRC.cpp \
	../../../Common/IntToString.cpp \
	../../../Common/Lang.cpp \
	../../../Common/ListFileUtils.cpp \
	../../../Common/MyString.cpp \
	../../../Common/MyVector.cpp \
	../../../Common/StringConvert.cpp \
	../../../Common/StringToInt.cpp \
	../../../Common/TextConfig.cpp \
	../../../Common/UTFConvert.cpp \
	../../../Common/Wildcard.cpp \
	../../../Windows/DLL.cpp \
	../../../Windows/Error.cpp \
	../../../Windows/FileDir.cpp \
	../../../Windows/FileFind.cpp \
	../../../Windows/FileIO.cpp \
	../../../Windows/FileName.cpp \
	../../../Windows/PropVariant.cpp \
	../../../Windows/PropVariantConversions.cpp \
	../../../Windows/Registry.cpp \
	../../../Windows/Synchronization.cpp \
	../../../Windows/Time.cpp \
	../../../Windows/System.cpp \
	../../../Windows/Window.cpp \
	../../../Windows/Control/Dialog.cpp \
	../../../Windows/Control/Controls.cpp \
	../../../Common/MyWindows.cpp \
	../../../myWindows/myGetTickCount.cpp \
	../../../myWindows/wine_date_and_time.cpp \
	../../../myWindows/wine_GetXXXDefaultLangID.cpp


SRCS_OUT=\
	../FileManager/HelpUtils.cpp \
	../FileManager/OpenCallback.cpp \
	../FileManager/RegistryUtils.cpp \
	../../../Common/NewHandler.cpp \
	../../../Windows/MemoryLock.cpp \
	../../../Windows/Registry.cpp \
	../../../Windows/ResourceString.cpp \
	../../../Windows/Shell.cpp

SRCS_C=\
	../../../../C/7zCrc.c \
	../../../../C/Threads.c

CompressDialog.o : CompressDialog.cpp
	$(CXX) $(CXXFLAGS) CompressDialog.cpp
CompressDialog_rc.o : CompressDialog_rc.cpp
	$(CXX) $(CXXFLAGS) CompressDialog_rc.cpp
ExtractDialog.o : ExtractDialog.cpp
	$(CXX) $(CXXFLAGS) ExtractDialog.cpp
ExtractDialog_rc.o : ExtractDialog_rc.cpp
	$(CXX) $(CXXFLAGS) ExtractDialog_rc.cpp
BenchmarkDialog.o : BenchmarkDialog.cpp
	$(CXX) $(CXXFLAGS) BenchmarkDialog.cpp
BenchmarkDialog_rc.o : BenchmarkDialog_rc.cpp
	$(CXX) $(CXXFLAGS) BenchmarkDialog_rc.cpp
ExtractGUI.o : ExtractGUI.cpp
	$(CXX) $(CXXFLAGS) ExtractGUI.cpp
GUI.o : GUI.cpp
	$(CXX) $(CXXFLAGS) GUI.cpp
wxGUI.o : wxGUI.cpp
	$(CXX) $(CXXFLAGS) wxGUI.cpp
UpdateCallbackGUI.o : UpdateCallbackGUI.cpp
	$(CXX) $(CXXFLAGS) UpdateCallbackGUI.cpp
UpdateGUI.o : UpdateGUI.cpp
	$(CXX) $(CXXFLAGS) UpdateGUI.cpp
ArchiveCommandLine.o : ../Common/ArchiveCommandLine.cpp
	$(CXX) $(CXXFLAGS) ../Common/ArchiveCommandLine.cpp
ArchiveExtractCallback.o : ../Common/ArchiveExtractCallback.cpp
	$(CXX) $(CXXFLAGS) ../Common/ArchiveExtractCallback.cpp
ArchiveOpenCallback.o : ../Common/ArchiveOpenCallback.cpp
	$(CXX) $(CXXFLAGS) ../Common/ArchiveOpenCallback.cpp
DefaultName.o : ../Common/DefaultName.cpp
	$(CXX) $(CXXFLAGS) ../Common/DefaultName.cpp
EnumDirItems.o : ../Common/EnumDirItems.cpp
	$(CXX) $(CXXFLAGS) ../Common/EnumDirItems.cpp
Extract.o : ../Common/Extract.cpp
	$(CXX) $(CXXFLAGS) ../Common/Extract.cpp
ExtractingFilePath.o : ../Common/ExtractingFilePath.cpp
	$(CXX) $(CXXFLAGS) ../Common/ExtractingFilePath.cpp
LoadCodecs.o : ../Common/LoadCodecs.cpp
	$(CXX) $(CXXFLAGS) ../Common/LoadCodecs.cpp
OpenArchive.o : ../Common/OpenArchive.cpp
	$(CXX) $(CXXFLAGS) ../Common/OpenArchive.cpp
PropIDUtils.o : ../Common/PropIDUtils.cpp
	$(CXX) $(CXXFLAGS) ../Common/PropIDUtils.cpp
SetProperties.o : ../Common/SetProperties.cpp
	$(CXX) $(CXXFLAGS) ../Common/SetProperties.cpp
SortUtils.o : ../Common/SortUtils.cpp
	$(CXX) $(CXXFLAGS) ../Common/SortUtils.cpp
TempFiles.o : ../Common/TempFiles.cpp
	$(CXX) $(CXXFLAGS) ../Common/TempFiles.cpp
Update.o : ../Common/Update.cpp
	$(CXX) $(CXXFLAGS) ../Common/Update.cpp
UpdateAction.o : ../Common/UpdateAction.cpp
	$(CXX) $(CXXFLAGS) ../Common/UpdateAction.cpp
UpdateCallback.o : ../Common/UpdateCallback.cpp
	$(CXX) $(CXXFLAGS) ../Common/UpdateCallback.cpp
UpdatePair.o : ../Common/UpdatePair.cpp
	$(CXX) $(CXXFLAGS) ../Common/UpdatePair.cpp
UpdateProduce.o : ../Common/UpdateProduce.cpp
	$(CXX) $(CXXFLAGS) ../Common/UpdateProduce.cpp
WorkDir.o : ../Common/WorkDir.cpp
	$(CXX) $(CXXFLAGS) ../Common/WorkDir.cpp
ZipRegistry.o : ../Common/ZipRegistry.cpp
	$(CXX) $(CXXFLAGS) ../Common/ZipRegistry.cpp
MyMessages.o : ../Explorer/MyMessages.cpp
	$(CXX) $(CXXFLAGS) ../Explorer/MyMessages.cpp
FormatUtils.o : ../FileManager/FormatUtils.cpp
	$(CXX) $(CXXFLAGS) ../FileManager/FormatUtils.cpp
ProgramLocation.o : ../FileManager/ProgramLocation.cpp
	$(CXX) $(CXXFLAGS) ../FileManager/ProgramLocation.cpp
ProgressDialog2.o : ../FileManager/ProgressDialog2.cpp
	$(CXX) $(CXXFLAGS) ../FileManager/ProgressDialog2.cpp
ProgressDialog2_rc.o : ../FileManager/ProgressDialog2_rc.cpp
	$(CXX) $(CXXFLAGS) ../FileManager/ProgressDialog2_rc.cpp
MessagesDialog.o : ../FileManager/MessagesDialog.cpp
	$(CXX) $(CXXFLAGS) ../FileManager/MessagesDialog.cpp
MessagesDialog_rc.o : ../FileManager/MessagesDialog_rc.cpp
	$(CXX) $(CXXFLAGS) ../FileManager/MessagesDialog_rc.cpp
OverwriteDialog.o : ../FileManager/OverwriteDialog.cpp
	$(CXX) $(CXXFLAGS) ../FileManager/OverwriteDialog.cpp
OverwriteDialog_rc.o : ../FileManager/OverwriteDialog_rc.cpp
	$(CXX) $(CXXFLAGS) ../FileManager/OverwriteDialog_rc.cpp
PasswordDialog.o : ../FileManager/PasswordDialog.cpp
	$(CXX) $(CXXFLAGS) ../FileManager/PasswordDialog.cpp
PasswordDialog_rc.o : ../FileManager/PasswordDialog_rc.cpp
	$(CXX) $(CXXFLAGS) ../FileManager/PasswordDialog_rc.cpp
ExtractCallback.o : ../FileManager/ExtractCallback.cpp
	$(CXX) $(CXXFLAGS) ../FileManager/ExtractCallback.cpp
SplitUtils.o : ../FileManager/SplitUtils.cpp
	$(CXX) $(CXXFLAGS) ../FileManager/SplitUtils.cpp
StringUtils.o : ../FileManager/StringUtils.cpp
	$(CXX) $(CXXFLAGS) ../FileManager/StringUtils.cpp
LangUtils.o : ../FileManager/LangUtils.cpp
	$(CXX) $(CXXFLAGS) ../FileManager/LangUtils.cpp
FilePathAutoRename.o : ../../Common/FilePathAutoRename.cpp
	$(CXX) $(CXXFLAGS) ../../Common/FilePathAutoRename.cpp
FileStreams.o : ../../Common/FileStreams.cpp
	$(CXX) $(CXXFLAGS) ../../Common/FileStreams.cpp
ProgressUtils.o : ../../Common/ProgressUtils.cpp
	$(CXX) $(CXXFLAGS) ../../Common/ProgressUtils.cpp
StreamUtils.o : ../../Common/StreamUtils.cpp
	$(CXX) $(CXXFLAGS) ../../Common/StreamUtils.cpp
CopyCoder.o : ../../Compress/CopyCoder.cpp
	$(CXX) $(CXXFLAGS) ../../Compress/CopyCoder.cpp
LzmaBench.o : ../../Compress/LZMA_Alone/LzmaBench.cpp
	$(CXX) $(CXXFLAGS) ../../Compress/LZMA_Alone/LzmaBench.cpp
CommandLineParser.o : ../../../Common/CommandLineParser.cpp
	$(CXX) $(CXXFLAGS) ../../../Common/CommandLineParser.cpp
CRC.o : ../../../Common/CRC.cpp
	$(CXX) $(CXXFLAGS) ../../../Common/CRC.cpp
IntToString.o : ../../../Common/IntToString.cpp
	$(CXX) $(CXXFLAGS) ../../../Common/IntToString.cpp
Lang.o : ../../../Common/Lang.cpp
	$(CXX) $(CXXFLAGS) ../../../Common/Lang.cpp
ListFileUtils.o : ../../../Common/ListFileUtils.cpp
	$(CXX) $(CXXFLAGS) ../../../Common/ListFileUtils.cpp
MyString.o : ../../../Common/MyString.cpp
	$(CXX) $(CXXFLAGS) ../../../Common/MyString.cpp
MyVector.o : ../../../Common/MyVector.cpp
	$(CXX) $(CXXFLAGS) ../../../Common/MyVector.cpp
StringConvert.o : ../../../Common/StringConvert.cpp
	$(CXX) $(CXXFLAGS) ../../../Common/StringConvert.cpp
StringToInt.o : ../../../Common/StringToInt.cpp
	$(CXX) $(CXXFLAGS) ../../../Common/StringToInt.cpp
TextConfig.o : ../../../Common/TextConfig.cpp
	$(CXX) $(CXXFLAGS) ../../../Common/TextConfig.cpp
UTFConvert.o : ../../../Common/UTFConvert.cpp
	$(CXX) $(CXXFLAGS) ../../../Common/UTFConvert.cpp
Wildcard.o : ../../../Common/Wildcard.cpp
	$(CXX) $(CXXFLAGS) ../../../Common/Wildcard.cpp
DLL.o : ../../../Windows/DLL.cpp
	$(CXX) $(CXXFLAGS) ../../../Windows/DLL.cpp
Error.o : ../../../Windows/Error.cpp
	$(CXX) $(CXXFLAGS) ../../../Windows/Error.cpp
FileDir.o : ../../../Windows/FileDir.cpp
	$(CXX) $(CXXFLAGS) ../../../Windows/FileDir.cpp
FileFind.o : ../../../Windows/FileFind.cpp
	$(CXX) $(CXXFLAGS) ../../../Windows/FileFind.cpp
FileIO.o : ../../../Windows/FileIO.cpp
	$(CXX) $(CXXFLAGS) ../../../Windows/FileIO.cpp
FileName.o : ../../../Windows/FileName.cpp
	$(CXX) $(CXXFLAGS) ../../../Windows/FileName.cpp
PropVariant.o : ../../../Windows/PropVariant.cpp
	$(CXX) $(CXXFLAGS) ../../../Windows/PropVariant.cpp
PropVariantConversions.o : ../../../Windows/PropVariantConversions.cpp
	$(CXX) $(CXXFLAGS) ../../../Windows/PropVariantConversions.cpp
Registry.o : ../../../Windows/Registry.cpp
	$(CXX) $(CXXFLAGS) ../../../Windows/Registry.cpp
Synchronization.o : ../../../Windows/Synchronization.cpp
	$(CXX) $(CXXFLAGS) ../../../Windows/Synchronization.cpp
Time.o : ../../../Windows/Time.cpp
	$(CXX) $(CXXFLAGS) ../../../Windows/Time.cpp
System.o : ../../../Windows/System.cpp
	$(CXX) $(CXXFLAGS) ../../../Windows/System.cpp
Window.o : ../../../Windows/Window.cpp
	$(CXX) $(CXXFLAGS) ../../../Windows/Window.cpp
Dialog.o : ../../../Windows/Control/Dialog.cpp
	$(CXX) $(CXXFLAGS) ../../../Windows/Control/Dialog.cpp
Controls.o : ../../../Windows/Control/Controls.cpp
	$(CXX) $(CXXFLAGS) ../../../Windows/Control/Controls.cpp
MyWindows.o : ../../../Common/MyWindows.cpp
	$(CXX) $(CXXFLAGS) ../../../Common/MyWindows.cpp
myGetTickCount.o : ../../../myWindows/myGetTickCount.cpp
	$(CXX) $(CXXFLAGS) ../../../myWindows/myGetTickCount.cpp
wine_date_and_time.o : ../../../myWindows/wine_date_and_time.cpp
	$(CXX) $(CXXFLAGS) ../../../myWindows/wine_date_and_time.cpp
wine_GetXXXDefaultLangID.o : ../../../myWindows/wine_GetXXXDefaultLangID.cpp
	$(CXX) $(CXXFLAGS) ../../../myWindows/wine_GetXXXDefaultLangID.cpp
Threads.o : ../../../../C/Threads.c
	$(CC) $(CFLAGS) ../../../../C/Threads.c

# CRC32, C version
7zCrc.o : ../../../../C/7zCrc.c
	$(CC) $(CFLAGS) ../../../../C/7zCrc.c
# CRC32, ASM version
7zCrcT8.o : ../../../../C/7zCrcT8.c
	$(CC) $(CFLAGS) ../../../../C/7zCrcT8.c

