PROG=../../../../bin/Client7z

LOCAL_FLAGS=-DCOMPRESS_MT

include ../../../../makefile.crc32
include ../../../../makefile.machine

LIBS=$(LOCAL_LIBS_DLL)

OBJS = \
wine_date_and_time.o \
MyWindows.o \
DLL.o \
FileDir.o \
FileFind.o \
FileIO.o \
FileName.o \
PropVariant.o \
PropVariantConversions.o \
IntToString.o \
MyString.o \
StringConvert.o \
MyVector.o \
Wildcard.o \
FileStreams.o \
Client7z.o

include ../../../../makefile.glb

