SRCS=\
../../../myWindows/wine_date_and_time.cpp \
../../../Windows/DLL.cpp \
../../../Windows/FileDir.cpp \
../../../Windows/FileFind.cpp \
../../../Windows/FileIO.cpp \
../../../Windows/FileName.cpp \
../../../Windows/PropVariant.cpp \
../../../Windows/PropVariantConversions.cpp \
../../../Common/IntToString.cpp \
../../../Common/MyWindows.cpp \
../../../Common/MyString.cpp \
../../../Common/StringConvert.cpp \
../../../Common/MyVector.cpp \
../../../Common/Wildcard.cpp \
../../Common/FileStreams.cpp \
./Client7z.cpp

wine_date_and_time.o : ../../../myWindows/wine_date_and_time.cpp
	$(CXX) $(CXXFLAGS) ../../../myWindows/wine_date_and_time.cpp
IntToString.o : ../../../Common/IntToString.cpp
	$(CXX) $(CXXFLAGS) ../../../Common/IntToString.cpp
MyWindows.o : ../../../Common/MyWindows.cpp
	$(CXX) $(CXXFLAGS) ../../../Common/MyWindows.cpp
MyString.o : ../../../Common/MyString.cpp
	$(CXX) $(CXXFLAGS) ../../../Common/MyString.cpp
StringConvert.o : ../../../Common/StringConvert.cpp
	$(CXX) $(CXXFLAGS) ../../../Common/StringConvert.cpp
MyVector.o : ../../../Common/MyVector.cpp
	$(CXX) $(CXXFLAGS) ../../../Common/MyVector.cpp
Wildcard.o : ../../../Common/Wildcard.cpp
	$(CXX) $(CXXFLAGS) ../../../Common/Wildcard.cpp
DLL.o : ../../../Windows/DLL.cpp
	$(CXX) $(CXXFLAGS) ../../../Windows/DLL.cpp
FileDir.o : ../../../Windows/FileDir.cpp
	$(CXX) $(CXXFLAGS) ../../../Windows/FileDir.cpp
FileFind.o : ../../../Windows/FileFind.cpp
	$(CXX) $(CXXFLAGS) ../../../Windows/FileFind.cpp
FileIO.o : ../../../Windows/FileIO.cpp
	$(CXX) $(CXXFLAGS) ../../../Windows/FileIO.cpp
FileName.o : ../../../Windows/FileName.cpp
	$(CXX) $(CXXFLAGS) ../../../Windows/FileName.cpp
PropVariant.o : ../../../Windows/PropVariant.cpp
	$(CXX) $(CXXFLAGS) ../../../Windows/PropVariant.cpp
PropVariantConversions.o : ../../../Windows/PropVariantConversions.cpp
	$(CXX) $(CXXFLAGS) ../../../Windows/PropVariantConversions.cpp
FileStreams.o : ../../Common/FileStreams.cpp
	$(CXX) $(CXXFLAGS) ../../Common/FileStreams.cpp
Client7z.o : ./Client7z.cpp
	$(CXX) $(CXXFLAGS) ./Client7z.cpp
