SRCS=\
ClassDefs.cpp \
../Agent/Agent.cpp \
../Agent/AgentOut.cpp \
../Agent/AgentProxy.cpp \
../Agent/ArchiveFolder.cpp \
../Agent/ArchiveFolderOpen.cpp \
../Agent/ArchiveFolderOut.cpp \
../Agent/UpdateCallbackAgent.cpp \
	App.cpp \
	wxFM.cpp \
	FM.cpp \
	FM_rc.cpp \
	OpenCallback.cpp \
	MyLoadMenu.cpp \
	Panel.cpp \
	PanelCrc.cpp \
	PanelCopy.cpp \
	PanelItems.cpp \
	PanelListNotify.cpp \
	PanelFolderChange.cpp \
	PanelItemOpen.cpp \
	PanelMenu.cpp \
	PanelOperations.cpp \
	PanelSelect.cpp \
	PanelSort.cpp \
	PanelSplitFile.cpp \
	PropertyName.cpp \
	RegistryUtils.cpp \
	ViewSettings.cpp \
	UpdateCallback100.cpp \
	RegistryAssociations.cpp \
	FileFolderPluginOpen.cpp \
	RootFolder.cpp \
	FSFolder.cpp \
	FSFolderCopy.cpp \
	FormatUtils.cpp \
	SysIconUtils.cpp \
	TextPairs.cpp \
	../Common/ArchiveName.cpp \
	../Common/CompressCall.cpp \
	../Common/WorkDir.cpp \
	ExtractCallback.cpp \
	ProgramLocation.cpp \
	CopyDialog.cpp \
	CopyDialog_rc.cpp \
	ListViewDialog.cpp \
	ListViewDialog_rc.cpp \
	SplitDialog.cpp \
	SplitDialog_rc.cpp \
	SplitUtils.cpp \
	StringUtils.cpp \
	ProgressDialog2.cpp \
	ProgressDialog2_rc.cpp \
	MessagesDialog.cpp \
	MessagesDialog_rc.cpp \
	ComboDialog.cpp \
	ComboDialog_rc.cpp \
	OverwriteDialog.cpp \
	OverwriteDialog_rc.cpp \
	PasswordDialog.cpp \
	PasswordDialog_rc.cpp \
	../Common/ArchiveExtractCallback.cpp \
	../Common/ArchiveOpenCallback.cpp \
	../Common/DefaultName.cpp \
	../Common/EnumDirItems.cpp \
	../Common/LoadCodecs.cpp \
	../Common/OpenArchive.cpp \
	../Common/ZipRegistry.cpp \
	../Common/ExtractingFilePath.cpp \
	../Common/PropIDUtils.cpp \
	../Common/SortUtils.cpp \
	../Common/UpdateAction.cpp \
	../Common/UpdateCallback.cpp \
	../Common/UpdatePair.cpp \
	../Common/UpdateProduce.cpp \
	../../Common/FilePathAutoRename.cpp \
	../../Common/FileStreams.cpp \
	../../Common/ProgressUtils.cpp \
	../../Common/StreamUtils.cpp \
	../../../Common/TextConfig.cpp \
	../../../Common/UTFConvert.cpp \
	../../Compress/CopyCoder.cpp \
	../../../Common/MyString.cpp \
	../../../Common/MyVector.cpp \
	../../../Common/StringConvert.cpp \
	../../../Common/StringToInt.cpp \
	../../../Common/MyWindows.cpp \
	../../../Common/Wildcard.cpp \
	../../../Windows/DLL.cpp \
	../../../Windows/Error.cpp \
	../../../Windows/FileDir.cpp \
	../../../Windows/FileFind.cpp \
	../../../Windows/FileIO.cpp \
	../../../Windows/FileName.cpp \
	../../../Windows/PropVariant.cpp \
	../../../Windows/PropVariantConversions.cpp \
	../../../Windows/Registry.cpp \
	../../../Windows/Synchronization.cpp \
	../../../Windows/Time.cpp \
	../../../Windows/Clipboard.cpp \
	../../../Windows/System.cpp \
	../../../Windows/Window.cpp \
	../../../Windows/Control/Dialog.cpp \
	../../../Windows/Control/Controls.cpp \
	../../../Windows/Control/Window2.cpp \
	LangUtils.cpp \
	../../../Common/Lang.cpp \
	../../../Common/CRC.cpp \
	../../../myWindows/wine_date_and_time.cpp \
	../../../myWindows/wine_GetXXXDefaultLangID.cpp

SRCS_OUT=\
	OpenCallbackGUI.cpp \
	UpdateCallbackGUI.cpp \
	UpdateGUI.cpp \
	../Common/ArchiveCommandLine.cpp \
	../Common/Extract.cpp \
	../Common/SetProperties.cpp \
	../Common/TempFiles.cpp \
	../Common/Update.cpp \
	../Explorer/MyMessages.cpp \
	../../../Common/CommandLineParser.cpp \
	../../../Common/IntToString.cpp \
	../../../Common/ListFileUtils.cpp \
	../../../myWindows/myGetTickCount.cpp \


SRCS_C=\
	../../../../C/7zCrc.c \
	../../../../C/Sort.c \
	../../../../C/Threads.c

##############################################################
ClassDefs.o : ClassDefs.cpp
	$(CXX) $(CXXFLAGS) ClassDefs.cpp
Agent.o : ../Agent/Agent.cpp
	$(CXX) $(CXXFLAGS) ../Agent/Agent.cpp
AgentOut.o : ../Agent/AgentOut.cpp
	$(CXX) $(CXXFLAGS) ../Agent/AgentOut.cpp
AgentProxy.o : ../Agent/AgentProxy.cpp
	$(CXX) $(CXXFLAGS) ../Agent/AgentProxy.cpp
ArchiveFolder.o : ../Agent/ArchiveFolder.cpp
	$(CXX) $(CXXFLAGS) ../Agent/ArchiveFolder.cpp
ArchiveFolderOpen.o : ../Agent/ArchiveFolderOpen.cpp
	$(CXX) $(CXXFLAGS) ../Agent/ArchiveFolderOpen.cpp
ArchiveFolderOut.o : ../Agent/ArchiveFolderOut.cpp
	$(CXX) $(CXXFLAGS) ../Agent/ArchiveFolderOut.cpp
UpdateCallbackAgent.o : ../Agent/UpdateCallbackAgent.cpp
	$(CXX) $(CXXFLAGS) ../Agent/UpdateCallbackAgent.cpp
##############################################################

CompressDialog.o : CompressDialog.cpp
	$(CXX) $(CXXFLAGS) CompressDialog.cpp
CompressDialog_rc.o : CompressDialog_rc.cpp
	$(CXX) $(CXXFLAGS) CompressDialog_rc.cpp
ExtractDialog.o : ExtractDialog.cpp
	$(CXX) $(CXXFLAGS) ExtractDialog.cpp
ExtractDialog_rc.o : ExtractDialog_rc.cpp
	$(CXX) $(CXXFLAGS) ExtractDialog_rc.cpp
BenchmarkDialog.o : BenchmarkDialog.cpp
	$(CXX) $(CXXFLAGS) BenchmarkDialog.cpp
BenchmarkDialog_rc.o : BenchmarkDialog_rc.cpp
	$(CXX) $(CXXFLAGS) BenchmarkDialog_rc.cpp
ExtractGUI.o : ExtractGUI.cpp
	$(CXX) $(CXXFLAGS) ExtractGUI.cpp
App.o : App.cpp
	$(CXX) $(CXXFLAGS) App.cpp
wxFM.o : wxFM.cpp
	$(CXX) $(CXXFLAGS) wxFM.cpp
FM.o : FM.cpp
	$(CXX) $(CXXFLAGS) FM.cpp
FM_rc.o : FM_rc.cpp
	$(CXX) $(CXXFLAGS) FM_rc.cpp
OpenCallback.o : OpenCallback.cpp
	$(CXX) $(CXXFLAGS) OpenCallback.cpp
MyLoadMenu.o : MyLoadMenu.cpp
	$(CXX) $(CXXFLAGS) MyLoadMenu.cpp
Panel.o : Panel.cpp
	$(CXX) $(CXXFLAGS) Panel.cpp
PanelCrc.o : PanelCrc.cpp
	$(CXX) $(CXXFLAGS) PanelCrc.cpp
PanelCopy.o : PanelCopy.cpp
	$(CXX) $(CXXFLAGS) PanelCopy.cpp
PanelItems.o : PanelItems.cpp
	$(CXX) $(CXXFLAGS) PanelItems.cpp
PanelListNotify.o : PanelListNotify.cpp
	$(CXX) $(CXXFLAGS) PanelListNotify.cpp
PanelFolderChange.o : PanelFolderChange.cpp
	$(CXX) $(CXXFLAGS) PanelFolderChange.cpp
PanelItemOpen.o : PanelItemOpen.cpp
	$(CXX) $(CXXFLAGS) PanelItemOpen.cpp
PanelMenu.o : PanelMenu.cpp
	$(CXX) $(CXXFLAGS) PanelMenu.cpp
PanelOperations.o : PanelOperations.cpp
	$(CXX) $(CXXFLAGS) PanelOperations.cpp
PanelSelect.o : PanelSelect.cpp
	$(CXX) $(CXXFLAGS) PanelSelect.cpp
PanelSort.o : PanelSort.cpp
	$(CXX) $(CXXFLAGS) PanelSort.cpp
PanelSplitFile.o : PanelSplitFile.cpp
	$(CXX) $(CXXFLAGS) PanelSplitFile.cpp
PropertyName.o : PropertyName.cpp
	$(CXX) $(CXXFLAGS) PropertyName.cpp
RegistryUtils.o : RegistryUtils.cpp
	$(CXX) $(CXXFLAGS) RegistryUtils.cpp
UpdateCallback100.o : UpdateCallback100.cpp
	$(CXX) $(CXXFLAGS) UpdateCallback100.cpp
ViewSettings.o : ViewSettings.cpp
	$(CXX) $(CXXFLAGS) ViewSettings.cpp
RegistryAssociations.o : RegistryAssociations.cpp
	$(CXX) $(CXXFLAGS) RegistryAssociations.cpp
FileFolderPluginOpen.o : FileFolderPluginOpen.cpp
	$(CXX) $(CXXFLAGS) FileFolderPluginOpen.cpp
RootFolder.o : RootFolder.cpp
	$(CXX) $(CXXFLAGS) RootFolder.cpp
FSFolder.o : FSFolder.cpp
	$(CXX) $(CXXFLAGS) FSFolder.cpp
FSFolderCopy.o : FSFolderCopy.cpp
	$(CXX) $(CXXFLAGS) FSFolderCopy.cpp
FormatUtils.o : FormatUtils.cpp
	$(CXX) $(CXXFLAGS) FormatUtils.cpp
SysIconUtils.o : SysIconUtils.cpp
	$(CXX) $(CXXFLAGS) SysIconUtils.cpp
TextPairs.o : TextPairs.cpp
	$(CXX) $(CXXFLAGS) TextPairs.cpp
OpenCallbackGUI.o : OpenCallbackGUI.cpp
	$(CXX) $(CXXFLAGS) OpenCallbackGUI.cpp
UpdateCallbackGUI.o : UpdateCallbackGUI.cpp
	$(CXX) $(CXXFLAGS) UpdateCallbackGUI.cpp
UpdateGUI.o : UpdateGUI.cpp
	$(CXX) $(CXXFLAGS) UpdateGUI.cpp
ArchiveCommandLine.o : ../Common/ArchiveCommandLine.cpp
	$(CXX) $(CXXFLAGS) ../Common/ArchiveCommandLine.cpp
ArchiveExtractCallback.o : ../Common/ArchiveExtractCallback.cpp
	$(CXX) $(CXXFLAGS) ../Common/ArchiveExtractCallback.cpp
ArchiveOpenCallback.o : ../Common/ArchiveOpenCallback.cpp
	$(CXX) $(CXXFLAGS) ../Common/ArchiveOpenCallback.cpp
DefaultName.o : ../Common/DefaultName.cpp
	$(CXX) $(CXXFLAGS) ../Common/DefaultName.cpp
EnumDirItems.o : ../Common/EnumDirItems.cpp
	$(CXX) $(CXXFLAGS) ../Common/EnumDirItems.cpp
Extract.o : ../Common/Extract.cpp
	$(CXX) $(CXXFLAGS) ../Common/Extract.cpp
ExtractingFilePath.o : ../Common/ExtractingFilePath.cpp
	$(CXX) $(CXXFLAGS) ../Common/ExtractingFilePath.cpp
LoadCodecs.o : ../Common/LoadCodecs.cpp
	$(CXX) $(CXXFLAGS) ../Common/LoadCodecs.cpp
OpenArchive.o : ../Common/OpenArchive.cpp
	$(CXX) $(CXXFLAGS) ../Common/OpenArchive.cpp
PropIDUtils.o : ../Common/PropIDUtils.cpp
	$(CXX) $(CXXFLAGS) ../Common/PropIDUtils.cpp
SetProperties.o : ../Common/SetProperties.cpp
	$(CXX) $(CXXFLAGS) ../Common/SetProperties.cpp
SortUtils.o : ../Common/SortUtils.cpp
	$(CXX) $(CXXFLAGS) ../Common/SortUtils.cpp
TempFiles.o : ../Common/TempFiles.cpp
	$(CXX) $(CXXFLAGS) ../Common/TempFiles.cpp
Update.o : ../Common/Update.cpp
	$(CXX) $(CXXFLAGS) ../Common/Update.cpp
UpdateAction.o : ../Common/UpdateAction.cpp
	$(CXX) $(CXXFLAGS) ../Common/UpdateAction.cpp
UpdateCallback.o : ../Common/UpdateCallback.cpp
	$(CXX) $(CXXFLAGS) ../Common/UpdateCallback.cpp
UpdatePair.o : ../Common/UpdatePair.cpp
	$(CXX) $(CXXFLAGS) ../Common/UpdatePair.cpp
UpdateProduce.o : ../Common/UpdateProduce.cpp
	$(CXX) $(CXXFLAGS) ../Common/UpdateProduce.cpp
WorkDir.o : ../Common/WorkDir.cpp
	$(CXX) $(CXXFLAGS) ../Common/WorkDir.cpp
ArchiveName.o : ../Common/ArchiveName.cpp
	$(CXX) $(CXXFLAGS) ../Common/ArchiveName.cpp
CompressCall.o : ../Common/CompressCall.cpp
	$(CXX) $(CXXFLAGS) ../Common/CompressCall.cpp
ZipRegistry.o : ../Common/ZipRegistry.cpp
	$(CXX) $(CXXFLAGS) ../Common/ZipRegistry.cpp
MyMessages.o : ../Explorer/MyMessages.cpp
	$(CXX) $(CXXFLAGS) ../Explorer/MyMessages.cpp
ProgramLocation.o : ProgramLocation.cpp
	$(CXX) $(CXXFLAGS) ProgramLocation.cpp
ComboDialog.o : ComboDialog.cpp
	$(CXX) $(CXXFLAGS) ComboDialog.cpp
ComboDialog_rc.o : ComboDialog_rc.cpp
	$(CXX) $(CXXFLAGS) ComboDialog_rc.cpp
CopyDialog.o : CopyDialog.cpp
	$(CXX) $(CXXFLAGS) CopyDialog.cpp
CopyDialog_rc.o : CopyDialog_rc.cpp
	$(CXX) $(CXXFLAGS) CopyDialog_rc.cpp
ListViewDialog.o : ListViewDialog.cpp
	$(CXX) $(CXXFLAGS) ListViewDialog.cpp
ListViewDialog_rc.o : ListViewDialog_rc.cpp
	$(CXX) $(CXXFLAGS) ListViewDialog_rc.cpp
SplitDialog.o : SplitDialog.cpp
	$(CXX) $(CXXFLAGS) SplitDialog.cpp
SplitDialog_rc.o : SplitDialog_rc.cpp
	$(CXX) $(CXXFLAGS) SplitDialog_rc.cpp
SplitUtils.o : SplitUtils.cpp
	$(CXX) $(CXXFLAGS) SplitUtils.cpp
ProgressDialog2.o : ProgressDialog2.cpp
	$(CXX) $(CXXFLAGS) ProgressDialog2.cpp
ProgressDialog2_rc.o : ProgressDialog2_rc.cpp
	$(CXX) $(CXXFLAGS) ProgressDialog2_rc.cpp
MessagesDialog.o : MessagesDialog.cpp
	$(CXX) $(CXXFLAGS) MessagesDialog.cpp
MessagesDialog_rc.o : MessagesDialog_rc.cpp
	$(CXX) $(CXXFLAGS) MessagesDialog_rc.cpp
OverwriteDialog.o : OverwriteDialog.cpp
	$(CXX) $(CXXFLAGS) OverwriteDialog.cpp
OverwriteDialog_rc.o : OverwriteDialog_rc.cpp
	$(CXX) $(CXXFLAGS) OverwriteDialog_rc.cpp
PasswordDialog.o : PasswordDialog.cpp
	$(CXX) $(CXXFLAGS) PasswordDialog.cpp
PasswordDialog_rc.o : PasswordDialog_rc.cpp
	$(CXX) $(CXXFLAGS) PasswordDialog_rc.cpp
ExtractCallback.o : ExtractCallback.cpp
	$(CXX) $(CXXFLAGS) ExtractCallback.cpp
StringUtils.o : StringUtils.cpp
	$(CXX) $(CXXFLAGS) StringUtils.cpp
LangUtils.o : LangUtils.cpp
	$(CXX) $(CXXFLAGS) LangUtils.cpp
FilePathAutoRename.o : ../../Common/FilePathAutoRename.cpp
	$(CXX) $(CXXFLAGS) ../../Common/FilePathAutoRename.cpp
FileStreams.o : ../../Common/FileStreams.cpp
	$(CXX) $(CXXFLAGS) ../../Common/FileStreams.cpp
ProgressUtils.o : ../../Common/ProgressUtils.cpp
	$(CXX) $(CXXFLAGS) ../../Common/ProgressUtils.cpp
StreamUtils.o : ../../Common/StreamUtils.cpp
	$(CXX) $(CXXFLAGS) ../../Common/StreamUtils.cpp
CopyCoder.o : ../../Compress/CopyCoder.cpp
	$(CXX) $(CXXFLAGS) ../../Compress/CopyCoder.cpp
LzmaBench.o : ../../Compress/LZMA_Alone/LzmaBench.cpp
	$(CXX) $(CXXFLAGS) ../../Compress/LZMA_Alone/LzmaBench.cpp
CommandLineParser.o : ../../../Common/CommandLineParser.cpp
	$(CXX) $(CXXFLAGS) ../../../Common/CommandLineParser.cpp
CRC.o : ../../../Common/CRC.cpp
	$(CXX) $(CXXFLAGS) ../../../Common/CRC.cpp
IntToString.o : ../../../Common/IntToString.cpp
	$(CXX) $(CXXFLAGS) ../../../Common/IntToString.cpp
Lang.o : ../../../Common/Lang.cpp
	$(CXX) $(CXXFLAGS) ../../../Common/Lang.cpp
ListFileUtils.o : ../../../Common/ListFileUtils.cpp
	$(CXX) $(CXXFLAGS) ../../../Common/ListFileUtils.cpp
MyString.o : ../../../Common/MyString.cpp
	$(CXX) $(CXXFLAGS) ../../../Common/MyString.cpp
MyVector.o : ../../../Common/MyVector.cpp
	$(CXX) $(CXXFLAGS) ../../../Common/MyVector.cpp
StringConvert.o : ../../../Common/StringConvert.cpp
	$(CXX) $(CXXFLAGS) ../../../Common/StringConvert.cpp
StringToInt.o : ../../../Common/StringToInt.cpp
	$(CXX) $(CXXFLAGS) ../../../Common/StringToInt.cpp
TextConfig.o : ../../../Common/TextConfig.cpp
	$(CXX) $(CXXFLAGS) ../../../Common/TextConfig.cpp
UTFConvert.o : ../../../Common/UTFConvert.cpp
	$(CXX) $(CXXFLAGS) ../../../Common/UTFConvert.cpp
Wildcard.o : ../../../Common/Wildcard.cpp
	$(CXX) $(CXXFLAGS) ../../../Common/Wildcard.cpp
DLL.o : ../../../Windows/DLL.cpp
	$(CXX) $(CXXFLAGS) ../../../Windows/DLL.cpp
Error.o : ../../../Windows/Error.cpp
	$(CXX) $(CXXFLAGS) ../../../Windows/Error.cpp
FileDir.o : ../../../Windows/FileDir.cpp
	$(CXX) $(CXXFLAGS) ../../../Windows/FileDir.cpp
FileFind.o : ../../../Windows/FileFind.cpp
	$(CXX) $(CXXFLAGS) ../../../Windows/FileFind.cpp
FileIO.o : ../../../Windows/FileIO.cpp
	$(CXX) $(CXXFLAGS) ../../../Windows/FileIO.cpp
FileName.o : ../../../Windows/FileName.cpp
	$(CXX) $(CXXFLAGS) ../../../Windows/FileName.cpp
PropVariant.o : ../../../Windows/PropVariant.cpp
	$(CXX) $(CXXFLAGS) ../../../Windows/PropVariant.cpp
PropVariantConversions.o : ../../../Windows/PropVariantConversions.cpp
	$(CXX) $(CXXFLAGS) ../../../Windows/PropVariantConversions.cpp
Registry.o : ../../../Windows/Registry.cpp
	$(CXX) $(CXXFLAGS) ../../../Windows/Registry.cpp
Synchronization.o : ../../../Windows/Synchronization.cpp
	$(CXX) $(CXXFLAGS) ../../../Windows/Synchronization.cpp
Time.o : ../../../Windows/Time.cpp
	$(CXX) $(CXXFLAGS) ../../../Windows/Time.cpp
Clipboard.o : ../../../Windows/Clipboard.cpp
	$(CXX) $(CXXFLAGS) ../../../Windows/Clipboard.cpp
System.o : ../../../Windows/System.cpp
	$(CXX) $(CXXFLAGS) ../../../Windows/System.cpp
Window.o : ../../../Windows/Window.cpp
	$(CXX) $(CXXFLAGS) ../../../Windows/Window.cpp
Dialog.o : ../../../Windows/Control/Dialog.cpp
	$(CXX) $(CXXFLAGS) ../../../Windows/Control/Dialog.cpp
Controls.o : ../../../Windows/Control/Controls.cpp
	$(CXX) $(CXXFLAGS) ../../../Windows/Control/Controls.cpp
Window2.o : ../../../Windows/Control/Window2.cpp
	$(CXX) $(CXXFLAGS) ../../../Windows/Control/Window2.cpp
MyWindows.o : ../../../Common/MyWindows.cpp
	$(CXX) $(CXXFLAGS) ../../../Common/MyWindows.cpp
myGetTickCount.o : ../../../myWindows/myGetTickCount.cpp
	$(CXX) $(CXXFLAGS) ../../../myWindows/myGetTickCount.cpp
wine_date_and_time.o : ../../../myWindows/wine_date_and_time.cpp
	$(CXX) $(CXXFLAGS) ../../../myWindows/wine_date_and_time.cpp
wine_GetXXXDefaultLangID.o : ../../../myWindows/wine_GetXXXDefaultLangID.cpp
	$(CXX) $(CXXFLAGS) ../../../myWindows/wine_GetXXXDefaultLangID.cpp
Sort.o : ../../../../C/Sort.c
	$(CC) $(CFLAGS) ../../../../C/Sort.c
Threads.o : ../../../../C/Threads.c
	$(CC) $(CFLAGS) ../../../../C/Threads.c

# CRC32, C version
7zCrc.o : ../../../../C/7zCrc.c
	$(CC) $(CFLAGS) ../../../../C/7zCrc.c
# CRC32, ASM version
7zCrcT8.o : ../../../../C/7zCrcT8.c
	$(CC) $(CFLAGS) ../../../../C/7zCrcT8.c

