SRCS=\
 ../../../myWindows/myGetTickCount.cpp \
 ../../../myWindows/wine_date_and_time.cpp \
 \
 ../../../Common/IntToString.cpp \
 ../../../Common/MyMap.cpp \
 ../../../Common/MyString.cpp \
 ../../../Common/MyWindows.cpp \
 ../../../Common/MyXml.cpp \
 ../../../Common/StringConvert.cpp \
 ../../../Common/StringToInt.cpp \
 ../../../Common/UTFConvert.cpp \
 ../../../Common/MyVector.cpp \
 ../../../Common/Wildcard.cpp \
 \
 ../../../Windows/FileDir.cpp \
 ../../../Windows/FileFind.cpp \
 ../../../Windows/FileIO.cpp \
 ../../../Windows/PropVariant.cpp \
 ../../../Windows/PropVariantUtils.cpp \
 ../../../Windows/Synchronization.cpp \
 ../../../Windows/System.cpp \
 ../../../Windows/Time.cpp \
 \
 ../../Common/InBuffer.cpp \
 ../../Common/InOutTempBuffer.cpp \
 ../../Common/CreateCoder.cpp \
 ../../Common/FilterCoder.cpp \
 ../../Common/LimitedStreams.cpp \
 ../../Common/LockedStream.cpp \
 ../../Common/MethodId.cpp \
 ../../Common/MethodProps.cpp \
 ../../Common/MemBlocks.cpp \
 ../../Common/OffsetStream.cpp \
 ../../Common/OutBuffer.cpp \
 ../../Common/OutMemStream.cpp \
 ../../Common/ProgressMt.cpp \
 ../../Common/ProgressUtils.cpp \
 ../../Common/StreamBinder.cpp \
 ../../Common/StreamObjects.cpp \
 ../../Common/StreamUtils.cpp \
 ../../Common/VirtThread.cpp \
 \
 ../../Archive/ArchiveExports.cpp \
 ../../Archive/DllExports2.cpp \
 ../../Archive/ArjHandler.cpp \
 ../../Archive/DebHandler.cpp \
 ../../Archive/DmgHandler.cpp \
 ../../Archive/ElfHandler.cpp \
 ../../Archive/MachoHandler.cpp \
 ../../Archive/MubHandler.cpp \
 ../../Archive/PeHandler.cpp \
 ../../Archive/RpmHandler.cpp \
 ../../Archive/XarHandler.cpp \
 ../../Archive/ZHandler.cpp \
 \
 ../../Archive/Common/CoderMixer2.cpp \
 ../../Archive/Common/CoderMixer2MT.cpp \
 ../../Archive/Common/CrossThreadProgress.cpp \
 ../../Archive/Common/DummyOutStream.cpp \
 ../../Archive/Common/FindSignature.cpp \
 ../../Archive/Common/InStreamWithCRC.cpp \
 ../../Archive/Common/ItemNameUtils.cpp \
 ../../Archive/Common/MultiStream.cpp \
 ../../Archive/Common/OutStreamWithCRC.cpp \
 ../../Archive/Common/OutStreamWithSha1.cpp \
 ../../Archive/Common/HandlerOut.cpp \
 ../../Archive/Common/ParseProperties.cpp \
 \
 ../../Archive/7z/7zCompressionMode.cpp \
 ../../Archive/7z/7zDecode.cpp \
 ../../Archive/7z/7zEncode.cpp \
 ../../Archive/7z/7zExtract.cpp \
 ../../Archive/7z/7zFolderInStream.cpp \
 ../../Archive/7z/7zFolderOutStream.cpp \
 ../../Archive/7z/7zHandler.cpp \
 ../../Archive/7z/7zHandlerOut.cpp \
 ../../Archive/7z/7zHeader.cpp \
 ../../Archive/7z/7zIn.cpp \
 ../../Archive/7z/7zOut.cpp \
 ../../Archive/7z/7zProperties.cpp \
 ../../Archive/7z/7zSpecStream.cpp \
 ../../Archive/7z/7zUpdate.cpp \
 ../../Archive/7z/7zRegister.cpp \
 \
 ../../Archive/BZip2/BZip2Handler.cpp \
 ../../Archive/BZip2/BZip2HandlerOut.cpp \
 ../../Archive/BZip2/BZip2Update.cpp \
 ../../Archive/BZip2/bz2Register.cpp \
 \
 ../../Archive/Cab/CabBlockInStream.cpp \
 ../../Archive/Cab/CabHandler.cpp \
 ../../Archive/Cab/CabHeader.cpp \
 ../../Archive/Cab/CabIn.cpp \
 ../../Archive/Cab/CabRegister.cpp \
 \
 ../../Archive/Chm/ChmHandler.cpp \
 ../../Archive/Chm/ChmHeader.cpp \
 ../../Archive/Chm/ChmIn.cpp \
 ../../Archive/Chm/ChmRegister.cpp \
 \
 ../../Archive/Com/ComHandler.cpp \
 ../../Archive/Com/ComIn.cpp \
 ../../Archive/Com/ComRegister.cpp \
 \
 ../../Archive/Cpio/CpioHandler.cpp \
 ../../Archive/Cpio/CpioHeader.cpp \
 ../../Archive/Cpio/CpioIn.cpp \
 ../../Archive/Cpio/CpioRegister.cpp \
 \
 ../../Archive/GZip/GZipHandler.cpp \
 ../../Archive/GZip/GZipHandlerOut.cpp \
 ../../Archive/GZip/GZipHeader.cpp \
 ../../Archive/GZip/GZipIn.cpp \
 ../../Archive/GZip/GZipOut.cpp \
 ../../Archive/GZip/GZipRegister.cpp \
 ../../Archive/GZip/GZipUpdate.cpp \
 \
 ../../Archive/Hfs/HfsHandler.cpp \
 ../../Archive/Hfs/HfsIn.cpp \
 ../../Archive/Hfs/HfsRegister.cpp \
 \
 ../../Archive/Iso/IsoHandler.cpp \
 ../../Archive/Iso/IsoHeader.cpp \
 ../../Archive/Iso/IsoIn.cpp \
 ../../Archive/Iso/IsoRegister.cpp \
 \
 ../../Archive/Lzh/LzhCRC.cpp \
 ../../Archive/Lzh/LzhHandler.cpp \
 ../../Archive/Lzh/LzhIn.cpp \
 ../../Archive/Lzh/LzhOutStreamWithCRC.cpp \
 ../../Archive/Lzh/LzhRegister.cpp \
 \
 ../../Archive/Lzma/LzmaArcRegister.cpp \
 ../../Archive/Lzma/LzmaFiltersDecode.cpp \
 ../../Archive/Lzma/LzmaHandler.cpp \
 ../../Archive/Lzma/LzmaIn.cpp \
 \
 ../../Archive/Nsis/NsisDecode.cpp \
 ../../Archive/Nsis/NsisHandler.cpp \
 ../../Archive/Nsis/NsisIn.cpp \
 ../../Archive/Nsis/NsisRegister.cpp \
 \
 ../../Archive/Rar/RarHandler.cpp \
 ../../Archive/Rar/RarHeader.cpp \
 ../../Archive/Rar/RarIn.cpp \
 ../../Archive/Rar/RarItem.cpp \
 ../../Archive/Rar/RarVolumeInStream.cpp \
 ../../Archive/Rar/RarRegister.cpp \
 \
 ../../Archive/Split/SplitHandler.cpp \
 ../../Archive/Split/SplitRegister.cpp \
 \
 ../../Archive/Tar/TarHandler.cpp \
 ../../Archive/Tar/TarHandlerOut.cpp \
 ../../Archive/Tar/TarHeader.cpp \
 ../../Archive/Tar/TarIn.cpp \
 ../../Archive/Tar/TarOut.cpp \
 ../../Archive/Tar/TarRegister.cpp \
 ../../Archive/Tar/TarUpdate.cpp \
 \
 ../../Archive/Udf/UdfHandler.cpp \
 ../../Archive/Udf/UdfIn.cpp \
 ../../Archive/Udf/UdfRegister.cpp \
 \
 ../../Archive/Wim/WimHandler.cpp \
 ../../Archive/Wim/WimIn.cpp \
 ../../Archive/Wim/WimRegister.cpp \
 \
 ../../Archive/Zip/ZipAddCommon.cpp \
 ../../Archive/Zip/ZipHandler.cpp \
 ../../Archive/Zip/ZipHandlerOut.cpp \
 ../../Archive/Zip/ZipHeader.cpp \
 ../../Archive/Zip/ZipIn.cpp \
 ../../Archive/Zip/ZipItem.cpp \
 ../../Archive/Zip/ZipOut.cpp \
 ../../Archive/Zip/ZipUpdate.cpp \
 ../../Archive/Zip/ZipRegister.cpp \
 \
 ../../Compress/CodecExports.cpp \
 ../../Compress/ArjDecoder1.cpp \
 ../../Compress/ArjDecoder2.cpp \
 ../../Compress/Bcj2Coder.cpp \
 ../../Compress/Bcj2Register.cpp \
 ../../Compress/BcjCoder.cpp \
 ../../Compress/BcjRegister.cpp \
 ../../Compress/BitlDecoder.cpp \
 ../../Compress/BranchCoder.cpp \
 ../../Compress/BranchMisc.cpp \
 ../../Compress/BranchRegister.cpp \
 ../../Compress/ByteSwap.cpp \
 ../../Compress/ByteSwapRegister.cpp \
 ../../Compress/BZip2Crc.cpp \
 ../../Compress/BZip2Decoder.cpp \
 ../../Compress/BZip2Encoder.cpp \
 ../../Compress/BZip2Register.cpp \
 ../../Compress/CopyCoder.cpp \
 ../../Compress/CopyRegister.cpp \
 ../../Compress/Deflate64Register.cpp \
 ../../Compress/DeflateDecoder.cpp \
 ../../Compress/DeflateEncoder.cpp \
 ../../Compress/DeflateNsisRegister.cpp \
 ../../Compress/DeflateRegister.cpp \
 ../../Compress/ImplodeDecoder.cpp \
 ../../Compress/ImplodeHuffmanDecoder.cpp \
 ../../Compress/LzhDecoder.cpp \
 ../../Compress/LzmaDecoder.cpp \
 ../../Compress/LzmaEncoder.cpp \
 ../../Compress/LzmaRegister.cpp \
 ../../Compress/LzOutWindow.cpp \
 ../../Compress/Lzx86Converter.cpp \
 ../../Compress/LzxDecoder.cpp \
 ../../Compress/PpmdDecoder.cpp \
 ../../Compress/PpmdEncoder.cpp \
 ../../Compress/PpmdRegister.cpp \
 ../../Compress/QuantumDecoder.cpp \
 ../../Compress/ShrinkDecoder.cpp \
 ../../Compress/ZlibDecoder.cpp \
 ../../Compress/ZDecoder.cpp \
 \
 ../../Compress/LZMA_Alone/LzmaBench.cpp \
 ../../Compress/LZMA_Alone/LzmaBenchCon.cpp \
 \
 ../../Crypto/7zAes.cpp \
 ../../Crypto/7zAesRegister.cpp \
 ../../Crypto/HmacSha1.cpp \
 ../../Crypto/MyAes.cpp \
 ../../Crypto/Pbkdf2HmacSha1.cpp \
 ../../Crypto/RandGen.cpp \
 ../../Crypto/Sha1.cpp \
 ../../Crypto/WzAes.cpp \
 ../../Crypto/Rar20Crypto.cpp \
 ../../Crypto/RarAes.cpp \
 ../../Crypto/ZipCrypto.cpp \
 ../../Crypto/ZipStrong.cpp

SRCS_C=\
 ../../../../C/Bra.c \
 ../../../../C/Bra86.c \
 ../../../../C/BraIA64.c \
 ../../../../C/BwtSort.c \
 ../../../../C/HuffEnc.c \
 ../../../../C/LzFind.c \
 ../../../../C/LzFindMt.c \
 ../../../../C/LzmaDec.c \
 ../../../../C/LzmaEnc.c \
 ../../../../C/Sort.c \
 ../../../../C/Threads.c \
 ../../../../C/Aes.c \
 ../../../../C/Sha256.c

include ../../../../makefile.rules

Main.o : ../../UI/Console/Main.cpp
	$(CXX) $(CXXFLAGS) ../../UI/Console/Main.cpp

